### ISSUE TITLE
Update DNS

### ISSUE THREAD

**Issue by sfjuggernaut** [keplerites/kepler#6]
See:
https://devcenter.heroku.com/articles/custom-domains

We need to have http://kepler452b.org/ point to the heroku app (https://nameless-inlet-37967.herokuapp.com/)

**Comment by sfjuggernaut** [comment]
<img width="803" alt="screen shot 2017-08-07 at 11 49 38 pm" src="https://user-images.githubusercontent.com/75023/29059632-659c0bae-7bcb-11e7-8ab3-9c27aa28c986.png">

Still have one issue to properly resolve.

**Comment by jpalmieri** [comment]
@sfjuggernaut any update on this?

**Comment by jpalmieri** [comment]
http://kepler452b.org now forwards to https://www.kepler452b.org and isn't causing any more ssl errors, so this seems to be resolved
